#!/bin/bash
#
#	Start the mysql database
#
bin=`dirname $0`
. $bin/dbenv.sh


#	Start the Docker container
echo docker run --name ${CONTAINER_NAME} -p ${SSH_PORT}:22 -p ${HTTP_PORT}:80 -p ${DB_PORT}:3306 --rm wnameless/mysql-phpmyadmin
docker run --name ${CONTAINER_NAME} -p ${SSH_PORT}:22 -p ${HTTP_PORT}:80 -p ${DB_PORT}:3306 --rm wnameless/mysql-phpmyadmin &

# Give it a chance to get running
sleep 2


# Make a few config fixes to the container and MySQL
# Allow access to MySql from non-localhost, by root user
# Copy SSH keys if they exist.
echo ""
echo "(Password is 'admin')"
TFILE="/tmp/$(basename $0).$$.tmp"
touch ${TFILE}

#
#	Install the SSH keys
#
keyfile=~/.ssh/id_rsa.pub
if [ -r ${keyfile} ] ; then

	key=`cat ${keyfile}`
	cat >> ${TFILE} << END1

	echo ''
	echo 'Installing SSH key file'
	mkdir .ssh
	cat >> ~/.ssh/authorized_keys << ENDKEY
${key}
ENDKEY
	chmod 700 .ssh
	chmod 644 .ssh/authorized_keys
END1
fi

#
#	Patch the MySQL config
#
patchConfig=Y
if [ ${patchConfig} == "Y" ] ; then

	cat >> ${TFILE} <<END2

	echo ''
	echo 'Patching /etc/mysql/my.cnf'
	sed -i 's/^bind-address/#bind-address/' /etc/mysql/my.cnf

	echo ''
	echo 'Shutting down mysql'
	mysqladmin -u root shutdown
	sleep 1

	echo ''
	echo 'Starting mysql'
	mysqld_safe &
	sleep 5

END2
fi

#
#	Give root permission to access from non-localhost
#
grantRootPerms=Y
if [ ${grantRootPerms} == "Y" ] ; then

	cat >> ${TFILE} <<END3
	echo ''
	echo 'Setting permissions for root database user.'
	TICK="\\\`"
	#cat << ENDSQL
	mysql -u root << ENDSQL
	CREATE DATABASE \${TICK}${DB_NAME}\${TICK} ;

	USE \${TICK}${DB_NAME}\${TICK} ;

	CREATE USER 'root'@'%' IDENTIFIED BY  '***';

	GRANT ALL PRIVILEGES ON  \${TICK}${DB_NAME}\${TICK} . * TO  'root'@'%' WITH GRANT OPTION ;

	SET PASSWORD FOR  'root'@'%' =  '';
ENDSQL
END3
fi

#
#	Display a nice message at the end
#
cat >> ${TFILE} <<END4
	echo ''
	echo ''
	echo 'Applications can now access the database at:'
	echo "      Host: ${DOCKER_IP}"
	echo "      Port: ${HTTP_PORT}"
	echo ''
	echo "Access phpMyAdmin at: http://${DOCKER_IP}:${HTTP_PORT}/phpmyadmin"
	echo ''
	echo ''
	echo 'Press Ctrl-C to continue...'
END4

#cat ${TFILE}
#exit 1
ssh root@${DOCKER_IP} -p ${SSH_PORT} /bin/bash -s < ${TFILE}

rm ${TFILE}
exit 0

