#!/bin/bash
#
#	Export the database to a local file.
#	This is VERY important, because the Docker container
#	will be destroyed as it is shut down.
#
bin=`dirname $0`
. $bin/dbenv.sh

#
# Find the highest numbered data file
#
last='0'
for file in ${bin}/${DB_NAME}.dump.* ; do
	suffix=`echo ${file} | sed 's/.*\.dump\.\(.*\)$/\1/'`
	num=`expr ${suffix} + 0 2>/dev/null` # Produces "" if non-numeric
	[ "$num" != "" ] && [ "$num" -gt ${last} ] && last=$num
done

if [ "${last}" == "0" ] ; then
	echo ""
	echo "Sorry, you don't have any data file to load"
	echo "Could not find ${bin}/${DB_NAME}.dump.1"
	echo ""
	exit 1
fi

# Display the file
dumpfile=${bin}/${DB_NAME}.dump.${last}
echo ""
echo "Loading this file:"
echo ""
ls -l $dumpfile

# Create the SQL file
TMPFILE="/tmp/$(basename $0).$$.tmp"
echo "connect \`${DB_NAME}\` ;" >> $TMPFILE
cat ${dumpfile} >> $TMPFILE

# Load the database
echo ''
echo Loading data...
echo "$" ssh root@${DOCKER_IP} -p ${SSH_PORT} mysql -u root "< ${TMPFILE}"
         ssh root@${DOCKER_IP} -p ${SSH_PORT} mysql -u root < ${TMPFILE}

# Tidy up
[ $? == 0 ] && rm ${TMPFILE}
exit 0
