#!/bin/bash
#
#	Export the database to a local file.
#	This is VERY important, because the Docker container
#	will be destroyed as it is shut down.
#
bin=`dirname $0`
. $bin/dbenv.sh

# Find a unique dump name
n=1
last='-'
while [ -e ${bin}/${DB_NAME}.dump.${n} ] ; do
	last=${n}
	n=`expr $n + 1`
done

if [ "${last}" == "-" ] ; then
	echo ""
	echo "Sorry, you don't have any data file to load"
	echo "Could not find ${bin}/${DB_NAME}.dump.1"
	echo ""
	exit 1
fi

# Display the file
dumpfile=${bin}/${DB_NAME}.dump.${last}
echo ''
ls -l $dumpfile

# Create the SQL file
TMPFILE="/tmp/$(basename $0).$$.tmp"
echo "connect \`${DB_NAME}\` ;" >> $TMPFILE
cat ${dumpfile} >> $TMPFILE

# Load the database
echo ''
echo Load data...
ssh root@${DOCKER_IP} -p ${SSH_PORT} mysql -u root < ${TMPFILE}

# Tidy up
rm ${TMPFILE}
exit 0
