#!/bin/bash
#
#	Use SSH to log into the Mysql Docker container.
#
bin=`dirname $0`
. $bin/dbenv.sh

echo "(password is 'admin')"
echo ssh root@${DOCKER_IP} -p ${SSH_PORT} "$@"
ssh root@${DOCKER_IP} -p ${SSH_PORT} "$@"
